apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cocklebur.fullname" . }}-config
  labels:
    {{- include "cocklebur.labels" . | nindent 4 }}
data:
  POPUP_APP_MODE: {{ .Values.config.appMode | quote }}
  POPUP_DATA_DIR: {{ .Values.config.dataDir | quote }}
  POPUP_BASE_URL: {{ .Values.config.baseUrl | quote }}
  POPUP_MAX_UPLOAD_MB: {{ .Values.config.maxUploadMb | quote }}
  POPUP_IMPORT_MAX_MB: {{ .Values.config.importMaxMb | quote }}
  POPUP_PROJECT_QUOTA_MB: {{ .Values.config.projectQuotaMb | quote }}
