{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cocklebur.fullname" . }}-secrets
  labels:
    {{- include "cocklebur.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.bootstrapKey }}
  COCKLEBUR_BOOTSTRAP_KEY: {{ .Values.secrets.bootstrapKey | quote }}
  {{- end }}
  {{- if .Values.secrets.secretKey }}
  POPUP_SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  {{- end }}
{{- end }}
